/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.irfin.cafe.meal.view;

import net.irfin.cafe.mealcategory.view.*;
import net.irfin.cafe.app.util.DatabaseConnection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import net.irfin.cafe.MainApp;
import net.irfin.cafe.meal.entity.Meal;
import net.irfin.cafe.meal.repository.MealRepo;
import net.irfin.cafe.mealcategory.entity.MealCategory;
import net.irfin.cafe.mealcategory.repository.MealCategoryRepo;

/**
 *
 * @author Hansen, Irfin
 */
public class MealList extends javax.swing.JPanel {
    
    /**
     * Creates new form MealCategoryList
     */
    public MealList() {
        initComponents();
        inisialisasiTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        menuItemEdit = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMeal = new javax.swing.JTable();

        menuItemEdit.setText("Edit...");
        menuItemEdit.addActionListener(this::menuItemEditActionPerformed);
        popupMenu.add(menuItemEdit);

        jMenuItem2.setText("Cancel");
        popupMenu.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");

        setLayout(new java.awt.BorderLayout());

        btnNew.setText("New...");
        btnNew.addActionListener(this::btnNewActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        jLabel1.setFont(jLabel1.getFont().deriveFont((jLabel1.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabel1.getFont().getSize()+4));
        jLabel1.setText("Meals");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                        .addComponent(btnRefresh))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblMeal.setComponentPopupMenu(popupMenu);
        tblMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMealMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMeal);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        List<Meal> listMakanan;
        
        try {
            // Baca dari database record2 MealCategory
            var repo = new MealRepo(DatabaseConnection.getConnection());
            listMakanan = repo.getAll();
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat mengakses data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // tampilkan ke JTable
        var tm = (DefaultTableModel) tblMeal.getModel();
        tm.setRowCount(0);      // Kosongkan dahulu baris2 data
        for (Meal m : listMakanan) {
            var barisData = new Object[] {
                m.getId(),
                m.getCategory().getName(),
                m.getName() 
            };
            
            tm.addRow(barisData);
        }
        tblMeal.setModel(tm);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        var dlg = new MealCreateDlg(null);
        dlg.setLocationRelativeTo(MainApp.getMainWindow());
        dlg.setVisible(true);
        
        if (dlg.isClosedByOk())
            btnRefreshActionPerformed(evt);
    }//GEN-LAST:event_btnNewActionPerformed

    private void menuItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditActionPerformed
        // Ambil baris yg dipilih user
        int idxBarisDipilih = tblMeal.getSelectedRow();
        if (idxBarisDipilih == -1) {
            JOptionPane.showMessageDialog(this, "Select row you want to edit");
            return;
        }
        idxBarisDipilih = tblMeal.convertRowIndexToModel(idxBarisDipilih);
        
        // Ambil ID dan Nama dari data yg dipilih
        int idMeal = (int) tblMeal.getModel().getValueAt(idxBarisDipilih, COL_ID);

        var dlgEdit = new MealUpdateDlg(null, idMeal);
        dlgEdit.setLocationRelativeTo(MainApp.getMainWindow());
        dlgEdit.setVisible(true);
        
        if (dlgEdit.isClosedByOk()) {
            btnRefreshActionPerformed(evt);
        }
    }//GEN-LAST:event_menuItemEditActionPerformed

    private void tblMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMealMouseClicked
        // Cek apakah user double click dan dgn left button
        if (SwingUtilities.isLeftMouseButton(evt) && evt.getClickCount() > 1) {
            
            // Ambil baris yg dipilih user
            int idxBarisDipilih = tblMeal.getSelectedRow();
            if (idxBarisDipilih == -1) {
                JOptionPane.showMessageDialog(this, "Select row you want to edit");
                return;
            }
            idxBarisDipilih = tblMeal.convertRowIndexToModel(idxBarisDipilih);
            
            // Ambil ID dan Nama dari data yg dipilih
            int idMeal = (int) tblMeal.getModel().getValueAt(idxBarisDipilih, COL_ID);

            var dlgView = new MealViewDlg(null, idMeal);
            dlgView.setLocationRelativeTo(MainApp.getMainWindow());
            dlgView.setVisible(true);
        }
    }//GEN-LAST:event_tblMealMouseClicked

    private static final int COL_ID = 0;
    private static final int COL_CTGR_NAME = 1;
    private static final int COL_MEALS_NAME = 2;
    private void inisialisasiTableModel() {
        String[] colNames = {"ID", "Category Name", "Meals Name"};
        var tableModel = new DefaultTableModel(colNames, 0) {  // 0 = jml baris. Sengaja di-set nol karena biarkan nanti terisi saat user klik reload.
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblMeal.setModel(tableModel);
    }
    
    public void refreshData() {
        btnRefreshActionPerformed(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuItemEdit;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTable tblMeal;
    // End of variables declaration//GEN-END:variables

}
