/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.irfin.cafe.view;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author Hansen, Irfin
 */
public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    private MealCategoryList paneMealCtgrList;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        // resize window to fill 70% screen width and 80% screen height
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        var newWidth = (int) (screenSize.width * 0.8);
        var newHeight = (int) (screenSize.height * 0.7);
        setSize(newWidth, newHeight);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpAppMenu = new javax.swing.ButtonGroup();
        panelSidebar = new javax.swing.JPanel();
        tglbtnMealCtgr = new javax.swing.JToggleButton();
        tglbtnBeverageCtgr = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Cafe Demo");

        panelSidebar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGrpAppMenu.add(tglbtnMealCtgr);
        tglbtnMealCtgr.setText("Meal Category");
        tglbtnMealCtgr.addActionListener(this::tglbtnMealCtgrActionPerformed);

        btnGrpAppMenu.add(tglbtnBeverageCtgr);
        tglbtnBeverageCtgr.setText("Beverage Category");

        jLabel1.setFont(jLabel1.getFont().deriveFont((jLabel1.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabel1.getFont().getSize()+4));
        jLabel1.setText("App Menu");

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglbtnMealCtgr, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglbtnBeverageCtgr, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tglbtnMealCtgr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tglbtnBeverageCtgr)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglbtnMealCtgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglbtnMealCtgrActionPerformed
        // Periksa apakah content pane saat ini sudah menampilkan UI yg dimaksud.
        if (isPaneAlreadyDisplayed(paneMealCtgrList))
            return;

        // Create objek MealCategoryList dan tampung ke bagian tengah content.
        paneMealCtgrList = new MealCategoryList();
        System.out.println("New MealCategoryList created.");
        
        add(paneMealCtgrList, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_tglbtnMealCtgrActionPerformed

    private boolean isPaneAlreadyDisplayed(JPanel panel) {
        var centerComp = getCurrentContentPane();
        
        if (centerComp != null && centerComp == panel)
            return true;
        else
            return false;
    }
    
    private Component getCurrentContentPane() {
        Container content = getContentPane();
        BorderLayout layout = (BorderLayout) content.getLayout();
        
        return layout.getLayoutComponent(BorderLayout.CENTER);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpAppMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JToggleButton tglbtnBeverageCtgr;
    private javax.swing.JToggleButton tglbtnMealCtgr;
    // End of variables declaration//GEN-END:variables
}
