/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.irfin.cafe.view;

import net.irfin.cafe.util.DatabaseConnection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.irfin.cafe.MainApp;
import net.irfin.cafe.entity.MealCategory;
import net.irfin.cafe.repository.MealCategoryRepo;

/**
 *
 * @author Hansen, Irfin
 */
public class MealCategoryList extends javax.swing.JPanel {

    /**
     * Creates new form MealCategoryList
     */
    public MealCategoryList() {
        initComponents();
        inisialisasiTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMealCategory = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        btnNew.setText("New...");
        btnNew.addActionListener(this::btnNewActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(tblMealCategory);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        List<MealCategory> listKategori;
        
        try {
            // Baca dari database record2 MealCategory
            MealCategoryRepo repo = new MealCategoryRepo(DatabaseConnection.getConnection());
            listKategori = repo.getAll();
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat mengakses data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // tampilkan ke JTable
        var tm = (DefaultTableModel) tblMealCategory.getModel();
        tm.setRowCount(0);      // Kosongkan dahulu baris2 data
        for (MealCategory mc : listKategori) {
            var barisData = new Object[] { mc.getId(), mc.getName() };
            
            tm.addRow(barisData);
        }
        tblMealCategory.setModel(tm);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        CreateMealCategoryDlg dlg = new CreateMealCategoryDlg(null);
        dlg.setLocationRelativeTo(MainApp.getMainWindow());
        dlg.setVisible(true);
        
        // Panggil dlg.getReturnStatus utk mengetahui user menutup dialog ini dengan
        // memilih OK/Save atau tidak?
        
        var retStatus = dlg.getReturnStatus();
        System.out.println("retStatus = " + retStatus);
        if (retStatus == CreateMealCategoryDlg.RET_OK)
            btnRefreshActionPerformed(evt);
    }//GEN-LAST:event_btnNewActionPerformed

    private void inisialisasiTableModel() {
        String[] colNames = {"ID", "Category Name"};
        var tableModel = new DefaultTableModel(colNames, 0);  // 0 = jml baris. Sengaja di-set nol karena biarkan nanti terisi saat user klik reload.
        
        tblMealCategory.setModel(tableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMealCategory;
    // End of variables declaration//GEN-END:variables
}
